CFLAGS = /nologo /MT /W3 /EHsc /O2 
LDFLAGS = kernel32.lib gdi32.lib /nologo /subsystem:console

PROGS = poj2309

all: $(PROGS)

poj2309: 
        cl $(CFLAGS) $(HEADER) poj2309.cpp        \
        /link $(LDFLAGS) /out:poj2309.exe

clean:
	del *.exe *obj