CFLAGS = /nologo /MT /W3 /EHsc /O2 
LDFLAGS = kernel32.lib gdi32.lib /nologo /subsystem:console

PROGS = poj2253

all: $(PROGS)

poj2253: 
        cl $(CFLAGS) $(HEADER) poj2253.cpp        \
        /link $(LDFLAGS) /out:poj2253.exe

clean:
	del *.exe *obj